[tool.poetry]
name = "mlcourse.ai"
version = "0.1.1"
description = "Open Machine Learning course by ods.ai"
authors = ["Yury Kashnitsky <yury.kashnitsky@gmail.com>"]
license = "CCBY-4.0"

[tool.poetry.dependencies]
python = ">=3.8,<=3.9"
fonttools = "^4.28.5"
jupyter-book = "^0.12.1"
matplotlib = "^3.5.1"
numpy = "^1.21.5"
pandas = "^1.3.5"
pillow = "^8.4.0"
plotly = "^5.4.0"
pre-commit = "^2.13.0"
pydot = "^1.4.2"
pylatexenc = "^2.10"
pytesseract = "^0.3.8"
pyyaml = "^6.0"
reverse-geocoder = "^1.5.1"
seaborn = "^0.11.2"
scikit-learn = "^1.0.1"
scipy = "^1.7.3"
sphinx-jupyterbook-latex = "^0.4.6"
statsmodels = "^0.13.1"
ua-parser = "^0.10.0"
user_agents = "^2.2.0"
wordcloud = "1.8.1"
pydotplus = "2.0.2"
gdown = "4.2.0"
eli5 = "0.11.0"
ghp-import = "2.0.2"


[tool.poetry.dev-dependencies]
pylint = "^2.12.2"
black = {version = "^21.12b0", allow-prereleases = true}
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
