title : mlcourse.ai
author: Yury Kashnitsky (yorko)
logo: _static/img/mlcourse_ai_logo.jpg

# Short description about the book
description: >-
  Open Machine Learning course

execute:
  execute_notebooks           : cache
  run_in_temp: true
  timeout: -1

# exclude some content
exclude_patterns: [book/jupyter_english/*]

# HTML-specific settings
html:
  favicon                     : _static/img/favicon.ico 
  home_page_in_navbar         : true

# Interact link settings
notebook_interface            : "notebook"

# LaTeX settings
# bibtex_bibfiles:
#    - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

# sphinx:
#   config:
#     html_extra_path: ['_static/data']
#     html_extra_path: ['_static/img']
